import type { ChapterTheme } from './types';

/**
 * Chapter 1: an education platform that helps students figure out what to study.
 *
 * Every value is the product's own shipped token unless its note says
 * otherwise. Three values are derived, and each says why in `derived`.
 */
export const educationPlatform = {
  id: 'education-platform',
  title: 'Education platform',
  shared: {
    'font-display': "'Inter Variable', 'Inter', ui-sans-serif, system-ui, sans-serif",
    'font-sans': "'Inter Variable', 'Inter', ui-sans-serif, system-ui, sans-serif",
    'font-mono': "'Geist Mono Variable', 'Geist Mono', ui-monospace, 'SF Mono', monospace",
    'radius-sm': '8px',
    'radius-md': '12px',
    'radius-lg': '20px',
    'radius-xl': '28px',
    'radius-full': '999px',
    'control-sm': '44px',
    'control-md': '44px',
    'control-lg': '48px',
    'control-inset-md': '{space.4}',
    'card-radius': '{radius.lg}',
    'card-padding': '{space.4}',
    'modal-radius': '{radius.xl}',
    'toast-radius': '{radius.lg}',
    'heading-weight': '{font-weight.bold}',
    'button-danger-bg': '{danger.text}',
    'button-danger-bg-hover': '{danger.text}',
  },
  light: {
    'surface-base': '#F6F7F9',
    'surface-raised': '#FFFFFF',
    'surface-overlay': '#FFFFFF',
    'surface-muted': '#F3F4F7',
    'text-primary': '#14171F',
    'text-secondary': '#1E232F',
    'text-muted': '#505662',
    'text-disabled': '#868074',
    'text-inverse': '#F6F7F9',
    'border-subtle': '#DCDFE5',
    'border-default': '#C4C9D4',
    'border-strong': '#A4AAB7',
    'accent-base': '#1E63D2',
    'accent-hover': '#1850AA',
    'accent-pressed': '#1850AA',
    'accent-subtle': '#E9F0FC',
    'accent-text': '#1E63D2',
    'accent-strong': '#1850AA',
    'accent-on': '#FFFFFF',
    'focus-ring': '#1E63D2',
    'success-bg': '#2F9E52',
    'success-subtle': '#E7F4EC',
    'success-text': '#1E7A3D',
    'success-border': '#9DD2AE',
    'warning-bg': '#C2871B',
    'warning-subtle': '#FAF0DC',
    'warning-text': '#925B0E',
    'warning-border': '#E4C68F',
    'danger-bg': '#CF4A32',
    'danger-subtle': '#FBE9E5',
    'danger-text': '#AF3A25',
    'danger-border': '#E9A99D',
    'info-bg': '#7C5CFC',
    'info-subtle': '#EDEAFB',
    'info-text': '#6446C0',
    'info-border': '#C0B1FB',
    'control-border': '#878E9A',
    'elevation-sm': '0 1px 2px rgba(27, 26, 23, 0.05)',
    'elevation-md': '0 8px 24px rgba(27, 26, 23, 0.09), 0 2px 6px rgba(27, 26, 23, 0.05)',
    'elevation-lg': '0 20px 48px rgba(27, 26, 23, 0.13), 0 4px 12px rgba(27, 26, 23, 0.07)',
  },
  dark: {
    'surface-base': '#141419',
    'surface-raised': '#1E1E24',
    'surface-overlay': '#1E1E24',
    'surface-muted': '#23232A',
    'text-primary': '#F6F4EF',
    'text-secondary': '#E6E3DB',
    'text-muted': '#C3BFB6',
    'text-disabled': '#7D7B73',
    'text-inverse': '#141419',
    'border-subtle': '#312F37',
    'border-default': '#413F4A',
    'border-strong': '#494851',
    'accent-base': '#85ABD1',
    'accent-hover': '#9FBDDB',
    'accent-pressed': '#9FBDDB',
    'accent-subtle': '#1C2A3B',
    'accent-text': '#85ABD1',
    'accent-strong': '#B6CBE2',
    'accent-on': '#0C1118',
    'focus-ring': '#85ABD1',
    'success-bg': '#3FB56A',
    'success-subtle': '#16281D',
    'success-text': '#6FD79A',
    'success-border': '#26603C',
    'warning-bg': '#D6A03A',
    'warning-subtle': '#2A2213',
    'warning-text': '#E7BC65',
    'warning-border': '#6F5423',
    'danger-bg': '#E06A4E',
    'danger-subtle': '#2E1A16',
    'danger-text': '#F1937D',
    'danger-border': '#753A2C',
    'info-bg': '#9581F5',
    'info-subtle': '#211C33',
    'info-text': '#BBACFF',
    'info-border': '#4F4481',
    'control-border': '#6B6B74',
    'elevation-sm': '0 1px 3px rgba(0, 0, 0, 0.16)',
    'elevation-md': '0 8px 24px rgba(0, 0, 0, 0.3), 0 2px 6px rgba(0, 0, 0, 0.16)',
    'elevation-lg': '0 20px 48px rgba(0, 0, 0, 0.38), 0 4px 12px rgba(0, 0, 0, 0.24)',
  },
  derived: {
    'control-border':
      'The product draws field edges at 1.66:1 against white. WCAG 1.4.11 asks 3:1 for the edge that identifies a field, so this chapter uses the product neutral hue at 3:1. Recommended back to the product.',
    'button-danger-bg':
      'White on the product destructive red measures 4.49:1, a hair under 4.5. The button fill uses the product own danger foreground (6.1:1) instead. Recommended back to the product.',
    '*-border (status)':
      'The product has no status border token. Each is its solid colour mixed 40% into its soft colour.',
    'info-*':
      'The product shows Explore in purple. Explore is the only informational status these screens show, so the info role carries it here.',
  },
} satisfies ChapterTheme;
