/**
 * Emits src/tokens/tokens.css and src/tokens/tailwind.css from tokens.ts.
 *
 *   npm run tokens          write both files
 *   npm run check:tokens    fail if either file is stale or a token is broken
 *
 * Validation runs in both modes: every alias resolves, no alias loops, every
 * chapter override names a real token, and each chapter overrides the same
 * colours in light and dark.
 */
import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { chapters } from '../src/tokens/chapters';
import {
  aliasesIn,
  cssVar,
  flattenTokens,
  resolve,
  toCss,
  tokenIndex,
  type FlatToken,
} from '../src/tokens/flatten';
import { tailwindMap } from '../src/tokens/tailwind-map';

const root = (p: string) => fileURLToPath(new URL(`../${p}`, import.meta.url));
const CSS_OUT = root('src/tokens/tokens.css');
const TW_OUT = root('src/tokens/tailwind.css');

const HEADER = `/*
 * Generated by scripts/build-tokens.ts from src/tokens/tokens.ts.
 * Do not edit by hand: change tokens.ts and run \`npm run tokens\`.
 */
`;

const problems: string[] = [];
const all = flattenTokens();
const known = tokenIndex();

// ---------- validation ----------
for (const t of all) {
  for (const v of [t.value, t.light, t.dark]) {
    if (v === undefined) continue;
    if (!v.trim()) problems.push(`${t.name}: empty value`);
    for (const a of aliasesIn(v)) if (!known.has(a)) problems.push(`${t.name}: unknown alias {${a}}`);
  }
  if ((t.light === undefined) !== (t.dark === undefined)) problems.push(`${t.name}: has one theme but not the other`);
}
for (const ch of chapters) {
  for (const scope of ['shared', 'light', 'dark'] as const) {
    for (const [k, v] of Object.entries(ch[scope])) {
      if (!known.has(k)) problems.push(`chapter ${ch.id}: ${scope} overrides unknown token ${k}`);
      for (const a of aliasesIn(v)) if (!known.has(a)) problems.push(`chapter ${ch.id}: ${k} uses unknown alias {${a}}`);
    }
  }
  const l = Object.keys(ch.light).sort().join();
  const d = Object.keys(ch.dark).sort().join();
  if (l !== d) problems.push(`chapter ${ch.id}: light and dark override different tokens`);
}
for (const [ns, map] of Object.entries(tailwindMap)) {
  for (const [util, name] of Object.entries(map)) {
    if (!known.has(name)) problems.push(`tailwind ${ns}-${util}: unknown token ${name}`);
  }
}
if (!problems.length) {
  for (const t of all) {
    for (const mode of ['light', 'dark'] as const) {
      try {
        resolve(t.name, mode);
        for (const ch of chapters) resolve(t.name, mode, ch);
      } catch (e) {
        problems.push(String((e as Error).message));
      }
    }
  }
}
if (problems.length) {
  console.error(`Token build failed:\n  - ${problems.join('\n  - ')}`);
  process.exit(1);
}

// ---------- tokens.css ----------
const decl = (name: string, value: string) => `  ${cssVar(name)}: ${toCss(value)};`;
const block = (selector: string, lines: string[], comment?: string) =>
  `${comment ? `/* ${comment} */\n` : ''}${selector} {\n${lines.join('\n')}\n}\n`;

const isComponent = (t: FlatToken) => t.group === 'component';
const plainTokens = all.filter((t) => t.value !== undefined && !isComponent(t));
const componentTokens = all.filter(isComponent);
const themedTokens = all.filter((t) => t.light !== undefined);

const parts: string[] = [HEADER];
parts.push(
  block(':root', plainTokens.map((t) => decl(t.name, t.value!)), 'Theme-independent primitives: type, space, shape, motion, layers.'),
);
parts.push(
  block(
    ':root,\n[data-chapter]',
    componentTokens.map((t) => decl(t.name, t.value!)),
    'Component tokens. Declared on chapters too, so they re-resolve against a chapter\'s overrides.',
  ),
);
parts.push(
  block(
    ":root,\n[data-theme='light']",
    ['  color-scheme: light;', ...themedTokens.map((t) => decl(t.name, t.light!))],
    'Light theme, the default.',
  ),
);
parts.push(
  block(
    "[data-theme='dark']",
    ['  color-scheme: dark;', ...themedTokens.map((t) => decl(t.name, t.dark!))],
    'Dark theme. Ramps run the other way: step 50 is always the one nearest the canvas.',
  ),
);
for (const ch of chapters) {
  const sel = `[data-chapter='${ch.id}']`;
  parts.push(
    block(
      sel,
      [...Object.entries(ch.shared), ...Object.entries(ch.light)].map(([k, v]) => decl(k, v)),
      `Chapter: ${ch.title}. Shared and light overrides.`,
    ),
  );
  parts.push(
    block(
      `[data-theme='dark'] ${sel}`,
      Object.entries(ch.dark).map(([k, v]) => decl(k, v)),
      `Chapter: ${ch.title}. Dark overrides.`,
    ),
  );
}
const tokensCss = parts.join('\n');

// ---------- tailwind.css ----------
const reset = [
  'color',
  'font',
  'text',
  'font-weight',
  'leading',
  'tracking',
  'radius',
  'shadow',
  'inset-shadow',
  'drop-shadow',
  'text-shadow',
  'container',
  'ease',
].map((ns) => `  --${ns}-*: initial;`);
const bridge: string[] = [];
for (const [ns, map] of Object.entries(tailwindMap)) {
  for (const [util, name] of Object.entries(map)) bridge.push(`  --${ns}-${util}: var(${cssVar(name)});`);
}
const tailwindCss = `${HEADER}
/* Clear Tailwind's defaults so only token-backed utilities exist. */
@theme {
${reset.join('\n')}
}

/* Utility names, each backed by a token. \`inline\` keeps the var() reference,
   so utilities follow the theme and any chapter override at runtime. */
@theme inline {
${bridge.join('\n')}
}
`;

// ---------- write or check ----------
const check = process.argv.includes('--check');
const outputs: [string, string][] = [
  [CSS_OUT, tokensCss],
  [TW_OUT, tailwindCss],
];
if (check) {
  const stale = outputs.filter(([file, text]) => {
    try {
      return readFileSync(file, 'utf8') !== text;
    } catch {
      return true;
    }
  });
  if (stale.length) {
    console.error(`Stale token output (run \`npm run tokens\`):\n  - ${stale.map(([f]) => f).join('\n  - ')}`);
    process.exit(1);
  }
  console.log(`Tokens OK: ${all.length} tokens, ${chapters.length} chapter theme(s), outputs current.`);
} else {
  for (const [file, text] of outputs) writeFileSync(file, text);
  console.log(`Wrote ${all.length} tokens and ${chapters.length} chapter theme(s).`);
}
